GET http://localhost:8080/helloGet?name=Vasia&age=53
Accept: application/json
###

GET http://localhost:8080/helloGet2?name=Vasia&age=55
Accept: application/json


###
POST http://localhost:8080/hello
Content-Type: application/json

{
  "name": "   ",
  "age" : -27
}


###

POST http://localhost:8080/hello
Content-Type: application/json

{
  "name": "Дмитрий",
  "age" : 27
}


###

GET http://localhost:8080/error
Accept: application/json
###

GET http://localhost:8080/error/8054
Accept: application/json

###


GET http://localhost:8080/error/iae
Accept: application/json

###
