GET http://localhost:8080/helloGet?name=Vasia&age=53
Accept: application/json
###

GET http://localhost:8080/helloGet2?name=Vasia&age=55
Accept: application/json


###
POST http://localhost:8080/hello
Content-Type: application/json

{
  "name": "Dmitrii",
  "age" : 27
}


###
